spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:postgresql://localhost:5432/noloussim.db
    username:
    password:

