version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: mspr_java
    environment:
      POSTGRES_DB: arosaje
      POSTGRES_USER: noloussim
      POSTGRES_PASSWORD: noloussim
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data