version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: NolOusSim
    environment:
      POSTGRES_DB: arosaje_DB
      POSTGRES_USER: noloussim
      POSTGRES_PASSWORD: noloussim
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
